// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/admin","redirect":"/admin/sub-page","parentId":"3","id":"4"},"5":{"path":"/admin/sub-page","name":"sub-page","parentId":"3","id":"5"},"6":{"name":"成绩管理","path":"/grade","icon":"smile","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"分析管理","path":"/analysis","icon":"smile","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"老师管理","path":"/teacher","icon":"smile","parentId":"ant-design-pro-layout","id":"8"},"9":{"name":"学生管理","path":"/student","icon":"smile","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"/","redirect":"/grade","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"*","layout":false,"id":"11"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Grade__index" */'@/pages/Grade/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Analysis__index" */'@/pages/Analysis/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Teacher__index" */'@/pages/Teacher/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Student__index" */'@/pages/Student/index.tsx')),
'10': React.lazy(() => import('./EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/0-nebula/code/huixue/huixue_dashboard/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/0-nebula/code/huixue/huixue_dashboard/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
