// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from 'D:/0-nebula/code/huixue/huixue_dashboard/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import SmileOutlined from 'D:/0-nebula/code/huixue/huixue_dashboard/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { CrownOutlined, SmileOutlined };
