const subjects_inflection = {
  '语文': 'Yuwen',
  '语文班名':'YuwenB',
  '数学': 'Shuxue',
  '数学班名':'ShuxueB',
  '英语': 'Yingyu',
  '英语班名':'YingyuB',
  '物理': 'Wuli',
  '物理班名':'WuliB',
  '化学': 'Huaxue',
  '化学班名':'HuaxueB',
  '历史': 'Lishi',
  '历史班名':'LishiB',
  '政治': 'Zhengzhi',
  '政治班名':'ZhengzhiB',
  '生物': 'Shengwu',
  '生物班名':'ShengwuB',
  '地理': 'Dili',
  '地理班名':'DiliB',
  '语文校名':'YuwenD',
  '数学校名':'ShuxueD',
  '英语校名':'YingyuD',
  '物理校名':'WuliD',
  '化学校名':'HuaxueD',
  '历史校名':'LishiD',
  '政治校名':'ZhengzhiD',
  '生物校名':'ShengwuD',
  '地理校名':'DiliD',
}

export default subjects_inflection