export interface CompareScore {
  dili: number,
  dilib: number,
  dilid: number,
  huaxue: number,
  huaxueb: number,
  huaxued: number,
  lishi: number,
  lishib: number,
  lishid: number,
  shengwu: number,
  shengwub: number,
  shengwud: number,
  shuxue: number,
  shuxueb: number,
  shuxued: number,
  wuli: number,
  wulib: number,
  wulid: number,
  yingyu: number,
  yingyub: number,
  yingyud: number,
  yuwen: number,
  yuwenb: number,
  yuwend: number,
  zhengzhi: number,
  zhengzhib: number,
  zhengzhid: number,
  sumb: number,
  sumd: number,
  sum_: number
}

const subjects_inflection = {
  '语文': 'yuwen',
  '语文班名':'yuwenb',
  '数学': 'shuxue',
  '数学班名':'shuxueb',
  '英语': 'yingyu',
  '英语班名':'yingyub',
  '物理': 'wuli',
  '物理班名':'wulib',
  '化学': 'huaxue',
  '化学班名':'huaxueb',
  '历史': 'lishi',
  '历史班名':'lishib',
  '政治': 'zhengzhi',
  '政治班名':'zhengzhib',
  '生物': 'shengwu',
  '生物班名':'shengwub',
  '地理': 'dili',
  '地理班名':'dilib',
  '语文校名':'yuwend',
  '数学校名':'shuxued',
  '英语校名':'yingyud',
  '物理校名':'wulid',
  '化学校名':'huaxued',
  '历史校名':'lishid',
  '政治校名':'zhengzhid',
  '生物校名':'shengwud',
  '地理校名':'dilid',
}


export default {
    subjects_inflection
}